# Generated by Django 4.0.2 on 2022-02-04 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('speciality', models.IntegerField(
                    choices=[(1, 'Моторист'), (2, 'Автоэлектрик'), (3, 'Маляр'), (4, 'Вулканизаторщик'),
                             (5, 'Автожестянщик'), (6, 'Механик-диагност')], max_length=1,
                    verbose_name='Специализация')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('car_brand', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('car_model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время записи')),
                ('client',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.clientprofile',
                                   verbose_name='Клиент')),
                ('master',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_api.masterprofile',
                                   verbose_name='Мастер')),
            ],
        ),
    ]
